### ISSUE TITLE
Error: Cannot find module 'html-wiring'

### ISSUE THREAD

**Issue by bouiboui** [exaprint/generator-serverless#3]
```sh
$ yo serverless

     _-----_     ╭──────────────────────────╮
    |       |    │    Hello there, let's    │
    |--(o)--|    │    create a serverless   │
   `---------´   │  architecture together!  │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What is the project name: (sls) calculator
? What is the project name: calculator
? Enter the project description: Exa calculator
? Enter the project description: Exa calculator
? Version: (0.1.0)
? Version: 0.1.0
? Author name: bouiboui
? Author name: bouiboui
? Author email: julienbouisset@exagroup.biz
? Author email: julienbouisset<@exagroup.biz
   create package.json
   create .editorconfig
   create .eslintrc.json
   create .gitattributes
   create .gitignore
   create .npmrc
   create README.md
   create jsdoc.conf.json
   create serverless.yml
   create yarn.lock
   create bin\ci.sh
   create bin\deploy.sh
   create bin\function-lib.sh
   create bin\remove.sh
   create config\.env.dev
   create config\.env.prod
   create test\api.js
   create src\libs\README.md
   create src\models\README.md
   create src\helpers\loggedError.js
   create src\helpers\logger.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'html-wiring'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Julien\AppData\Roaming\npm\node_modules\generator-serverless\generators\route\index.js:5:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

**Comment by tomexa** [comment]
Forgot the `--save` when installed html-wiring.
It's now been fixed with release 1.0.2.
